// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenPageLogo_screen_init(void)
{
    ui_ScreenPageLogo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageLogo, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_ScreenPageLogo, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenPageLogo, lv_color_hex(0x0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPageLogo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    imageLogo = lv_img_create(ui_ScreenPageLogo);
    lv_img_set_src(imageLogo, &pngLogoSkyGarage);
    lv_obj_align(imageLogo, LV_ALIGN_CENTER, 0, 0);
}
